// src/repositories/embeddingRepository.ts
//
// The interface for storing and searching chunk embeddings — mirrors the
// existing DocumentRepository pattern (see documentRepository.ts): an
// interface here describes *what* the rest of the app can do, and a concrete
// class elsewhere (postgresEmbeddingRepository.ts) describes *how* it's
// actually done against a real database. Routes/services depend only on this
// interface, never on the Postgres-specific implementation directly.
//
// .NET parallel: identical to defining IEmbeddingRepository and registering a
// concrete PostgresEmbeddingRepository against it in a DI container
// (services.AddScoped<IEmbeddingRepository, PostgresEmbeddingRepository>()).
// The benefit is the same one DocumentRepository already demonstrates: the
// storage technology can change (or be swapped for a test double) without
// touching anything that depends on the interface.

// One row of the chunk_embeddings table, as a plain TypeScript object —
// this is the shape callers work with; the SQL column names (snake_case)
// only exist inside postgresEmbeddingRepository.ts.
export interface ChunkEmbeddingRecord {
  id: string;
  documentId: string;
  chunkIndex: number;
  chunkText: string;
  // A plain JS array of numbers. The Postgres `vector` type serialization
  // (converting this to/from Postgres's vector wire format) is handled
  // entirely by the pgvector type registration in src/config/db.ts — nothing
  // in this interface (or in callers) needs to know that conversion happens.
  embedding: number[];
  createdAt: Date;
}

export interface EmbeddingRepository {
  // Inserts one chunk + its embedding. Takes everything except `id` and
  // `createdAt` because those are generated by the database (see schema.sql's
  // DEFAULT gen_random_uuid() / DEFAULT now()) — the caller shouldn't invent
  // its own id or timestamp when the database can guarantee a correct one.
  insert(record: Omit<ChunkEmbeddingRecord, 'id' | 'createdAt'>): Promise<ChunkEmbeddingRecord>;

  // Given a query embedding, returns up to `limit` stored chunks ordered by
  // similarity — closest match first. `distance` is included in the result
  // (rather than a plain array of records) so callers can see *how* similar
  // each match is, e.g. to filter out weak matches later once real retrieval
  // logic is built (Day 2+). Smaller distance = more similar; see
  // postgresEmbeddingRepository.ts for why (cosine distance, not similarity).
  //
  // This searches EVERY row in the table, across every document — kept
  // around because it's still the right tool for a genuinely global search,
  // but real per-document retrieval (Day 2+) should use
  // findSimilarInDocument below instead. See docs/week-2-day-2.md's
  // "why does retrieval need to be scoped to one document?" section for why
  // an unscoped search is the wrong default once more than one document's
  // chunks are in the table.
  findSimilar(embedding: number[], limit: number): Promise<Array<ChunkEmbeddingRecord & { distance: number }>>;

  // Same idea as findSimilar, but scoped to one document's chunks only —
  // this is a genuinely different operation, not findSimilar with an
  // optional filter bolted on, because "search everything" and "search one
  // document" should never be silently interchangeable at a call site. Used
  // by the retrieval service (src/services/retrieval.ts) behind the
  // POST /documents/:id/query route.
  findSimilarInDocument(
    documentId: string,
    embedding: number[],
    limit: number,
  ): Promise<Array<ChunkEmbeddingRecord & { distance: number }>>;

  // Atomically replaces every chunk belonging to one document: deletes
  // whatever's currently stored for `documentId`, then inserts the new set,
  // as a single database transaction (either both steps happen, or neither
  // does). This is what makes calling POST /documents/:id/embed a second
  // time for the same document safe — it re-chunks and re-embeds cleanly
  // instead of piling up duplicate rows next to the old ones, and a crash
  // mid-operation can never leave the document with a half-deleted,
  // half-inserted set of chunks. See docs/week-2-day-2.md's "database
  // transactions" section for the full reasoning.
  replaceChunksForDocument(
    documentId: string,
    chunks: Array<Omit<ChunkEmbeddingRecord, 'id' | 'createdAt' | 'documentId'>>,
  ): Promise<ChunkEmbeddingRecord[]>;

  // Used by POST /documents/:id/query to distinguish "this document has
  // never been embedded" (a 422 — the caller needs to call /embed first)
  // from "this document has chunks, but none of them matched well" (a
  // legitimate empty/weak result set from findSimilarInDocument). Those are
  // different situations that deserve different responses, and
  // findSimilarInDocument returning zero rows can't tell them apart on its
  // own — an empty array is ambiguous between the two.
  countChunksForDocument(documentId: string): Promise<number>;
}
