// src/repositories/embeddingRepository.ts
//
// The interface for storing and searching chunk embeddings — mirrors the
// existing DocumentRepository pattern (see documentRepository.ts): an
// interface here describes *what* the rest of the app can do, and a concrete
// class elsewhere (postgresEmbeddingRepository.ts) describes *how* it's
// actually done against a real database. Routes/services depend only on this
// interface, never on the Postgres-specific implementation directly.
//
// .NET parallel: identical to defining IEmbeddingRepository and registering a
// concrete PostgresEmbeddingRepository against it in a DI container
// (services.AddScoped<IEmbeddingRepository, PostgresEmbeddingRepository>()).
// The benefit is the same one DocumentRepository already demonstrates: the
// storage technology can change (or be swapped for a test double) without
// touching anything that depends on the interface.

// One row of the chunk_embeddings table, as a plain TypeScript object —
// this is the shape callers work with; the SQL column names (snake_case)
// only exist inside postgresEmbeddingRepository.ts.
export interface ChunkEmbeddingRecord {
  id: string;
  documentId: string;
  chunkIndex: number;
  chunkText: string;
  // A plain JS array of numbers. The Postgres `vector` type serialization
  // (converting this to/from Postgres's vector wire format) is handled
  // entirely by the pgvector type registration in src/config/db.ts — nothing
  // in this interface (or in callers) needs to know that conversion happens.
  embedding: number[];
  createdAt: Date;
}

export interface EmbeddingRepository {
  // Inserts one chunk + its embedding. Takes everything except `id` and
  // `createdAt` because those are generated by the database (see schema.sql's
  // DEFAULT gen_random_uuid() / DEFAULT now()) — the caller shouldn't invent
  // its own id or timestamp when the database can guarantee a correct one.
  insert(record: Omit<ChunkEmbeddingRecord, 'id' | 'createdAt'>): Promise<ChunkEmbeddingRecord>;

  // Given a query embedding, returns up to `limit` stored chunks ordered by
  // similarity — closest match first. `distance` is included in the result
  // (rather than a plain array of records) so callers can see *how* similar
  // each match is, e.g. to filter out weak matches later once real retrieval
  // logic is built (Day 2+). Smaller distance = more similar; see
  // postgresEmbeddingRepository.ts for why (cosine distance, not similarity).
  findSimilar(embedding: number[], limit: number): Promise<Array<ChunkEmbeddingRecord & { distance: number }>>;
}
